- name: Login to Docker Hub
  docker_login:
    username: ramzeus1
    password: dckr_pat_pC4gjbebQ4Z4PAFVN4VcK8XTsAs
#  no_log: true

- name: Pull Docker image
  docker_image:
    name: ramzeus1/devops-info-service
    tag: "{{ docker_image_tag }}"
    source: pull
    force_source: yes

- name: Stop existing container
  docker_container:
    name: "{{ app_container_name }}"
    state: stopped
  ignore_errors: yes

- name: Remove existing container
  docker_container:
    name: "{{ app_container_name }}"
    state: absent
  ignore_errors: yes

- name: Run new container
  docker_container:
    name: "{{ app_container_name }}"
    image: ramzeus1/devops-info-service:{{ docker_image_tag }}
    state: started
    restart_policy: "{{ restart_policy }}"
    ports:
      - "{{ app_port }}:5000"
    env:
      HOST: "0.0.0.0"
      PORT: "5000"

- name: Wait for application to be ready
  wait_for:
    port: "{{ app_port }}"
    host: 127.0.0.1
    delay: 5
    timeout: 30

- name: Verify health endpoint
  uri:
    url: http://127.0.0.1:{{ app_port }}/health
    method: GET
    status_code: 200
  register: health_result

- name: Display health check
  debug:
    msg: "Health check: {{ health_result.json.status }} (uptime: {{ health_result.json.uptime_seconds }}s)"
