---
- name: Provision web servers
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - role: common
      tags:
        - common

    - role: docker
      tags:
        - docker

  tasks:
    - name: Provisioning completed
      debug:
        msg: "System provisioning completed successfully"
      tags:
        - always